export enum PaymentMethodEnum {
	CASH = "CASH",
	CARD = "CARD",
	DEBIT_CARD = "DEBIT_CARD",
	BANK_TRANSFER = "BANK_TRANSFER",
	PAYPAL = "PAYPAL",
	APPLE_PAY = "APPLE_PAY",
	GOOGLE_PAY = "GOOGLE_PAY",
	CRYPTO = "CRYPTO",
	INVOICE = "INVOICE",
	CHECK = "CHECK",
	MOBILE_PAYMENT = "MOBILE_PAYMENT",
	GIFT_CARD = "GIFT_CARD",
	OTHER = "OTHER"
}
